### ISSUE TITLE
PackageId is typo'd

### ISSUE THREAD

**Issue by Beyley** [brianpursley/Npgmq#6]
https://github.com/brianpursley/Npgmq/blob/1c2360b81b1aee3f323ad242ddb467ec01cb0e3a/Npgmq/Npgmq.csproj#L8C20-L8C25

P and G are swapped, which includes the nuget package
https://www.nuget.org/packages/Ngpmq

**Comment by brianpursley** [comment]
:facepalm: 

Thank you for opening an issue for this @Beyley

Working on fixing it now...

**Comment by brianpursley** [comment]
Fixed and updated Nuget pakage.
https://www.nuget.org/packages/Npgmq

Old package is now deprecated with a redirect to the correctly named package.

Thanks again, @Beyley
