### ISSUE TITLE
Hyphens in queue names are not escaped

### ISSUE THREAD

**Issue by Beyley** [brianpursley/Npgmq#7]
```
Npgmq.NpgmqException: Failed to poll queue image-worker-queue.
 ---> Npgsql.PostgresException (0x80004005): 42601: syntax error at or near "-"
   at Npgsql.Internal.NpgsqlConnector.ReadMessageLong(Boolean async, DataRowLoadingMode dataRowLoadingMode, Boolean readingNotifications, Boolean isReadingPrependedMessage)
   at System.Runtime.CompilerServices.PoolingAsyncValueTaskMethodBuilder`1.StateMachineBox`1.System.Threading.Tasks.Sources.IValueTaskSource<TResult>.GetResult(Int16 token)
   at Npgsql.NpgsqlDataReader.NextResult(Boolean async, Boolean isConsuming, CancellationToken cancellationToken)
   at Npgsql.NpgsqlDataReader.NextResult(Boolean async, Boolean isConsuming, CancellationToken cancellationToken)
   at Npgsql.NpgsqlCommand.ExecuteReader(Boolean async, CommandBehavior behavior, CancellationToken cancellationToken)
   at Npgsql.NpgsqlCommand.ExecuteReader(Boolean async, CommandBehavior behavior, CancellationToken cancellationToken)
   at Npgmq.NpgmqClient.PollBatchAsync[T](String queueName, Int32 vt, Int32 limit, Int32 pollTimeoutSeconds, Int32 pollIntervalMilliseconds)
   at Npgmq.NpgmqClient.PollBatchAsync[T](String queueName, Int32 vt, Int32 limit, Int32 pollTimeoutSeconds, Int32 pollIntervalMilliseconds)
  Exception data:
    Severity: ERROR
    SqlState: 42601
    MessageText: syntax error at or near "-"
    InternalPosition: 95
    InternalQuery: 
          WITH cte AS
          (
              SELECT msg_id
              FROM pgmq.q_image-worker-queue
              WHERE vt <= clock_timestamp()
              ORDER BY msg_id ASC
              LIMIT $1
              FOR UPDATE SKIP LOCKED
          )
          UPDATE pgmq.q_image-worker-queue m
          SET
              vt = clock_timestamp() + interval '30 seconds',
              read_ct = read_ct + 1
          FROM cte
          WHERE m.msg_id = cte.msg_id
          RETURNING m.msg_id, m.read_ct, m.enqueued_at, m.vt, m.message;
          
    Where: PL/pgSQL function pgmq.read_with_poll(text,integer,integer,integer,integer) line 35 at FOR over EXECUTE statement
    File: scan.l
    Line: 1241
    Routine: scanner_yyerror
```

**Comment by brianpursley** [comment]
Hmm, this seems like it could be a [pgmq](https://github.com/tembo-io/pgmq) issue.

Since it uses the queue name as part of a table name without escaping it, it's going to fail for anything that doesn't work unescaped.

@Beyley I see you are attempting to poll, but before that, were you able to actually create a queue named `image-worker-queue`?

When I try to create a queue named this directly using pgmq, it fails:
```
postgres=# SELECT pgmq.create('image-worker-queue');
ERROR:  syntax error at or near "-"
LINE 2:     CREATE TABLE IF NOT EXISTS pgmq.q_image-worker-queue (
                                                   ^
QUERY:  
    CREATE TABLE IF NOT EXISTS pgmq.q_image-worker-queue (
        msg_id BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
        read_ct INT DEFAULT 0 NOT NULL,
        enqueued_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
        vt TIMESTAMP WITH TIME ZONE NOT NULL,
        message JSONB
    )
    
CONTEXT:  PL/pgSQL function pgmq.create_non_partitioned(text) line 5 at EXECUTE
SQL statement "SELECT pgmq.create_non_partitioned(queue_name)"
PL/pgSQL function pgmq."create"(text) line 3 at PERFORM
```

You may want to open this as an issue in [pgmq](https://github.com/tembo-io/pgmq/issues).

I'm not a pgmq maintainer, but it sounds like it would be reasonable for it to either:
1. Fail with a more helpful message like "invalid queue name" or something like that.
2. Escape all DDL operations so that hyphens and other characters are supported.

What do you think?

**Comment by Beyley** [comment]
> before that, were you able to actually create a queue named `image-worker-queue`?
> 
> When I try to create a queue named this directly using pgmq, it fails:
> You may want to open this as an issue in [pgmq](https://github.com/tembo-io/pgmq/issues?q=sort%3Aupdated-desc+is%3Aissue+is%3Aopen).

My code at the time of hitting the issue wasn't creating the queue at the right time, so I saw the poll fail due to invalid syntax before the create fail, which is why I saw that first. Creating one with that name does fail for me aswell.

> I'm not a pgmq maintainer, but it sounds like it would be reasonable for it to either:
> 
>     1. Fail with a more helpful message like "invalid queue name" or something like that.
> 
>     2. Escape all DDL operations so that hyphens and other characters are supported.
> 
> 
> What do you think?

I think number two is the ideal solution, I'll go open an issue over there, if one does not exist already

**Comment by brianpursley** [comment]
I see you opened the issue on pgmq. Closing this one for now, but we can re-open if there is anything specific to Npgmq's client implementation.
